---
title: Merqurio.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: merqur.io
description: The thoughts of Gabriel de Maeztu on Medicine and Technology
author: Gabriel de Maeztu
url: http://merqur.io
baseurl: 
author-bio: I'm a medical student based in Barcelona and a self-made data scientist.
  I love Medicine, coding and data mining.
author-bio2: Right now I work in the crosspoint of these amazing fields exploring
  the deep secrets of the brain thanks to MRI Technology.
twitter: gabimaeztu
github: merqurio
linkedin: gabrieldemaeztu
dribbble: 
instagram: 
ga_domain: merqur.io
ga_tracking_id: UA-25316413-7
markdown: kramdown
permalink: pretty
highlighter: rouge
paginate: 10
paginate_path: "/page/:num"
sass:
  sass_dir: _scss
  style: compressed
